In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly.express as px
import plotly.graph_objs as go
from geopy.geocoders import Nominatim
import folium
from folium.plugins import HeatMap
from folium.plugins import FastMarkerCluster
from plotly import tools
import re
from plotly.offline import init_notebook_mode, plot, iplot
from wordcloud import WordCloud, STOPWORDS 
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('nashik.csv',index_col=0)

In [4]:
df

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft
0,"Sheetal Vihar, Bhagwant Nagar, Dr.Homi Bhabha ...",Mahendra Kotwal,Apartment,old,3.0,75.00,39.72,1550.0
1,"Samraat Dream Citi, Samta Nagar, Nashik",Jiten Dadarkar,Apartment,old,2.0,41.00,21.71,1000.0
2,"Suryaprakash Apartment,Nashik Road, Nashik",Pankaj,Apartment,old,2.0,53.35,28.25,970.0
3,"Adishvar Residency,Nashik Road, Nashik",Saurav,Apartment,old,2.0,55.00,29.13,1000.0
4,"Nashik Road, Nashik",Vivek Pavanaskar,Apartment,old,2.0,27.00,14.30,853.0
...,...,...,...,...,...,...,...,...
5492,"Vasantdadanagar, Adgaon,Nashik",Geeta Buildcon,Independent_house,old,2.0,NaN,NaN,NaN
5493,"Samarth Nagar, Makhmalabad,Nashik",Atharvashree Buildmat Private Limited,Independent_house,old,2.0,34.32,18.17,NaN
5494,"Bhor Town Ship, Nashik",Shree Prakash Developers,Independent_house,old,NaN,NaN,NaN,NaN
5495,"Chandshi, Nashik",Nirman Group,Independent_house,old,NaN,NaN,NaN,NaN
5496,"Medage Nagar, Nashik",Ashoka Realty,Independent_house,old,1.0,11.38,6.02,NaN

In [36]:
df1 =df.iloc[0:500]
df1

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft
0,"Sheetal Vihar, Bhagwant Nagar, Dr.Homi Bhabha ...",Mahendra Kotwal,Apartment,old,3.0,75.00,39.72,1550.0
1,"Samraat Dream Citi, Samta Nagar, Nashik",Jiten Dadarkar,Apartment,old,2.0,41.00,21.71,1000.0
2,"Suryaprakash Apartment,Nashik Road, Nashik",Pankaj,Apartment,old,2.0,53.35,28.25,970.0
3,"Adishvar Residency,Nashik Road, Nashik",Saurav,Apartment,old,2.0,55.00,29.13,1000.0
4,"Nashik Road, Nashik",Vivek Pavanaskar,Apartment,old,2.0,27.00,14.30,853.0
...,...,...,...,...,...,...,...,...
495,"Dwarka, Nashik",Gauri Tani,Apartment,old,3.0,75.00,39.72,1800.0
496,"Ojhar, Nashik",SANJAY PAWAR,Apartment,old,1.0,18.00,9.53,600.0
497,"Vijaynagar Colony, Nashik",Chandrashekhar Jagtap,Apartment,old,1.0,17.00,9.00,420.0
498,"Panchavati, Nashik",Bharat Patil,Apartment,old,1.0,30.00,15.89,900.0
499,"Kala Nagar, Indira Nagar,Nashik",Rajendra Jadhav,Apartment,old,2.0,46.00,24.36,1050.0

In [5]:
from geopy.geocoders import ArcGIS
nom=ArcGIS()

In [37]:
df1['cordinates']= df1['address'].apply(nom.geocode)
df1['latitude'] = df1['cordinates'].apply(lambda x:x.latitude)
df1['longitude'] = df1['cordinates'].apply(lambda x:x.longitude)

df1.to_csv('df1')

In [11]:
df1.to_csv('df1')

In [12]:
df1

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft,cordinates
0,"Sheetal Vihar, Bhagwant Nagar, Dr.Homi Bhabha ...",Mahendra Kotwal,Apartment,old,3.0,75.00,39.72,1550.0,"(Sheetal Vihar, (19.987960000000044, 73.787390..."
1,"Samraat Dream Citi, Samta Nagar, Nashik",Jiten Dadarkar,Apartment,old,2.0,41.00,21.71,1000.0,"(Samraat Dream Citi, (19.98246000000006, 73.81..."
2,"Suryaprakash Apartment,Nashik Road, Nashik",Pankaj,Apartment,old,2.0,53.35,28.25,970.0,"(Surya Prakash, (19.975850000000037, 73.788750..."
3,"Adishvar Residency,Nashik Road, Nashik",Saurav,Apartment,old,2.0,55.00,29.13,1000.0,"(Nashik Road, Vadner Dumala, Nashik, Maharasht..."
4,"Nashik Road, Nashik",Vivek Pavanaskar,Apartment,old,2.0,27.00,14.30,853.0,"(Nashik Road, Nashik, Maharashtra, (19.9553100..."
...,...,...,...,...,...,...,...,...,...
495,"Dwarka, Nashik",Gauri Tani,Apartment,old,3.0,75.00,39.72,1800.0,"(Dwarka, Nashik, Maharashtra, (19.993070000000..."
496,"Ojhar, Nashik",SANJAY PAWAR,Apartment,old,1.0,18.00,9.53,600.0,"(Ojhar, Niphd, Nashik, Maharashtr, (20.0969100..."
497,"Vijaynagar Colony, Nashik",Chandrashekhar Jagtap,Apartment,old,1.0,17.00,9.00,420.0,"(Vijaynagar, Deola, Nashik, Maharashtra, (20.4..."
498,"Panchavati, Nashik",Bharat Patil,Apartment,old,1.0,30.00,15.89,900.0,"(Panchavati, Nashik, Maharashtra, (20.01678000..."
499,"Kala Nagar, Indira Nagar,Nashik",Rajendra Jadhav,Apartment,old,2.0,46.00,24.36,1050.0,"(Kala Nagar, Indira Nagar, Nashik, Maharashtra..."

In [51]:
df2 =df.iloc[500:1000]

df2['cordinates'] = df2['address'].apply(nom.geocode)
df2['latitude'] = df2['cordinates'].apply(lambda x:x.latitude)
df2['longitude'] = df2['cordinates'].apply(lambda x:x.longitude)

df2.to_csv('df2')

In [6]:
df3 =df.iloc[1000:1500]

df3['cordinates'] = df3['address'].apply(nom.geocode)

In [26]:
df3.to_csv('df3')

In [8]:
df4 =df.iloc[1500:2000]

df4['cordinates'] = df4['address'].apply(nom.geocode)

In [27]:
df4.to_csv('df4')

In [29]:
df5=df.iloc[2000:2500]

df5['cordinates'] = df5['address'].apply(nom.geocode)
df5['latitude'] = df5['cordinates'].apply(lambda x:x.latitude)
df5['longitude'] = df5['cordinates'].apply(lambda x:x.longitude)

df5.to_csv('df5')

In [31]:
df6=df.iloc[2500:3000]

df6['cordinates'] = df6['address'].apply(nom.geocode)
df6['latitude'] = df6['cordinates'].apply(lambda x:x.latitude)
df6['longitude'] = df6['cordinates'].apply(lambda x:x.longitude)

df6.to_csv('df6')

In [32]:
df7=df.iloc[3000:3500]

df7['cordinates'] = df7['address'].apply(nom.geocode)
df7['latitude'] = df7['cordinates'].apply(lambda x:x.latitude)
df7['longitude'] = df7['cordinates'].apply(lambda x:x.longitude)

df7.to_csv('df7')

In [33]:
df8=df.iloc[3500:4000]

df8['cordinates'] = df8['address'].apply(nom.geocode)
df8['latitude'] = df8['cordinates'].apply(lambda x:x.latitude)
df8['longitude'] = df8['cordinates'].apply(lambda x:x.longitude)

df8.to_csv('df8')

In [34]:
df9=df.iloc[4000:4500]

df9['cordinates'] = df9['address'].apply(nom.geocode)
df9['latitude'] = df9['cordinates'].apply(lambda x:x.latitude)
df9['longitude'] = df9['cordinates'].apply(lambda x:x.longitude)

df9.to_csv('df9')

In [35]:
df10=df.iloc[4500:5000]

df10['cordinates'] = df10['address'].apply(nom.geocode)
df10['latitude'] = df10['cordinates'].apply(lambda x:x.latitude)
df10['longitude'] = df10['cordinates'].apply(lambda x:x.longitude)

df10.to_csv('df10')

In [40]:
df11=df.iloc[5000:5496]

df11['cordinates'] = df11['address'].apply(nom.geocode)
df11['latitude'] = df11['cordinates'].apply(lambda x:x.latitude)
df11['longitude'] = df11['cordinates'].apply(lambda x:x.longitude)

df11.to_csv('df11')

In [ ]:
df5=df.iloc[2000:2500]

df5['cordinates'] = df5['address'].apply(nom.geocode)
df5['latitude'] = df5['cordinates'].apply(lambda x:x.latitude)
df5['longitude'] = df5['cordinates'].apply(lambda x:x.longitude)

df5.to_csv('df5')

In [52]:
df1 = pd.read_csv('df1',index_col=0)
df2 = pd.read_csv('df2',index_col=0)
df3 = pd.read_csv('df3',index_col=0)
df4 = pd.read_csv('df4',index_col=0)
df5 = pd.read_csv('df5',index_col=0)
df6 = pd.read_csv('df6',index_col=0)
df7 = pd.read_csv('df7',index_col=0)
df8 = pd.read_csv('df8',index_col=0)
df9 = pd.read_csv('df9',index_col=0)
df10 = pd.read_csv('df10',index_col=0)
df11 = pd.read_csv('df11',index_col=0)

In [53]:
frames= [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11]

final_data= pd.concat(frames,axis=0)

In [54]:
final_data

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft,cordinates,latitude,longitude
0,"Sheetal Vihar, Bhagwant Nagar, Dr.Homi Bhabha ...",Mahendra Kotwal,Apartment,old,3.0,75.00,39.72,1550.0,Sheetal Vihar,19.987960,73.787390
1,"Samraat Dream Citi, Samta Nagar, Nashik",Jiten Dadarkar,Apartment,old,2.0,41.00,21.71,1000.0,Samraat Dream Citi,19.982460,73.811840
2,"Suryaprakash Apartment,Nashik Road, Nashik",Pankaj,Apartment,old,2.0,53.35,28.25,970.0,Surya Prakash,19.975850,73.788750
3,"Adishvar Residency,Nashik Road, Nashik",Saurav,Apartment,old,2.0,55.00,29.13,1000.0,"Nashik Road, Vadner Dumala, Nashik, Maharashtr...",19.930532,73.811734
4,"Nashik Road, Nashik",Vivek Pavanaskar,Apartment,old,2.0,27.00,14.30,853.0,"Nashik Road, Nashik, Maharashtra",19.955310,73.840890
...,...,...,...,...,...,...,...,...,...,...,...
5491,"Prashant Nagar, Pathardi Phata,Nashik",Datta Kale,Independent_house,old,4.0,92.25,45.80,NaN,"Prashant Nagar, Pathardi Phata, Nashik, Mahara...",19.951040,73.756990
5492,"Vasantdadanagar, Adgaon,Nashik",Geeta Buildcon,Independent_house,old,2.0,NaN,NaN,NaN,"Vasantdada Nagar, Adgaon, Nashik, Maharashtra",20.031780,73.855100
5493,"Samarth Nagar, Makhmalabad,Nashik",Atharvashree Buildmat Private Limited,Independent_house,old,2.0,34.32,18.17,NaN,"Samarth Nagar, Makhamalabad, Nashik, Maharashtra",20.049050,73.796960
5494,"Bhor Town Ship, Nashik",Shree Prakash Developers,Independent_house,old,NaN,NaN,NaN,NaN,"Town Ship Colony, Panchavati, Nashik, Maharashtra",20.027090,73.821100
5495,"Chandshi, Nashik",Nirman Group,Independent_house,old,NaN,NaN,NaN,NaN,"Chandshi, Nashik Sub-District, Nashik, Maharas...",20.038750,73.750250

In [55]:
final_data.isnull().sum()

address               0
owners               13
housetype             0
house_condition       0
BHK                 163
price               954
per_month_emi       960
total_sqft         1511
cordinates            0
latitude              0
longitude             0
dtype: int64

In [60]:
final_data['housetype'].replace({'Independent_house':'Independent house'},inplace=True)

In [61]:
final_data.to_csv('final_data')

In [56]:
df4.head(40)

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft,cordinates,latitude,longitude
1500,"Pimpalgaon Bahula, Nashik",Yogisai Construction,Apartment,old,1.0,NaN,NaN,NaN,"Pimpalgaon Bahula, Nashik, Maharashtra",19.979460,73.708830
1501,"Pimpalgaon Bahula, Nashik",Nandan Devlopers,Apartment,old,1.0,NaN,NaN,NaN,"Pimpalgaon Bahula, Nashik, Maharashtra",19.979460,73.708830
1502,"Professor Colony, Nashik",Jadhav Builders Nashik,Apartment,old,2.0,NaN,NaN,NaN,"Professors Colony Road, Panchavati, Nashik, Ma...",20.017267,73.785088
1503,"Wasan Nagar, Pathardi Phata,Nashik",Sahyadri Buildcon Nashik,Apartment,old,1.0,NaN,NaN,NaN,"Wasan Nagar, Pathardi Phata, Nashik, Maharashtra",19.956910,73.762330
1504,"Makhmalabad, Nashik",Shree Sagar Associates,Apartment,old,1.0,NaN,NaN,NaN,"Makhmalabad, Makhamalabad, Nashik, Maharashtra",20.047230,73.775450
1505,"Saptashrungi Nagar, Kamatwade Gaon,Nashik",Rashmi Narendra Jadhav Builders And Developers,Apartment,old,NaN,NaN,NaN,NaN,"Saptashrungi Nagar, Nashik, Maharashtra",19.974420,73.833810
1506,"Takle Nagar, Krishna Nagar,Nashik",Shreeved Builders And Developers,Apartment,old,1.0,20.28,10.74,NaN,"Krishna Nagar, Cidco, Nashik, Maharashtra",19.967800,73.752310
1507,"Panchavati, Nashik",Shri Sai Buildcon Nashik,Apartment,old,1.0,NaN,NaN,NaN,"Panchavati, Nashik, Maharashtra",20.016780,73.796650
1508,"Murari Nagar, Nashik",SM Buildcon,Apartment,old,1.0,NaN,NaN,NaN,"Murari Nagar, Cidco, Nashik, Maharashtra",19.971920,73.746480
1509,"Indira Nagar, Nashik",Laxmi Construction And Developer,Apartment,old,1.0,NaN,NaN,NaN,"Indira Nagar, Nashik, Maharashtra",19.972190,73.783500
1510,"Gandhi Nagar Airport Area, Deolali Gaon,Nashik",Karda Infrastructure,Apartment,old,2.0,NaN,NaN,NaN,"Gandhi Nagar Airport Area, Gandhi Nagar, Nashi...",19.946250,73.814700
1511,"Prashant Nagar, Pathardi Phata,Nashik",Vikas Gemini,Apartment,old,1.0,NaN,NaN,NaN,"Prashant Nagar, Pathardi Phata, Nashik, Mahara...",19.951040,73.756990
1512,"Chandshi, Nashik",Sushant Gangurde,Apartment,old,2.0,26.22,13.88,NaN,"Chandshi, Nashik Sub-District, Nashik, Maharas...",20.038750,73.750250
1513,"Chandshi, Nashik",Suyojit Infrastructure Pvt Ltd.,Apartment,old,1.0,29.68,15.72,NaN,"Chandshi, Nashik Sub-District, Nashik, Maharas...",20.038750,73.750250
1514,"Viveka Nand Nagar, Anandwalli Gaon,Nashik",Hardik Developers,Apartment,old,3.0,34.65,18.35,NaN,"Vivekanand Nagar, Anandvalli, Nashik, Maharashtra",20.010830,73.747380
1515,"Shinde, Nashik",Rajee Infrastructure,Apartment,old,1.0,13.92,7.37,NaN,"Shinde, Nashik Sub-District, Nashik, Maharashtra",19.917850,73.900680
1516,"Ghadge Nagar, Makhmalabad,Nashik",Hasmukhbhai Jerambhai Suhagiya Construction An...,Apartment,old,1.0,17.27,9.14,NaN,"Ghadage Nagar, Makhamalabad, Nashik, Maharashtra",20.033570,73.784240
1517,"Vasantdadanagar, Adgaon,Nashik",Matoshri Buildcon,Apartment,old,1.0,NaN,NaN,NaN,"Vasantdada Nagar, Adgaon, Nashik, Maharashtra",20.031780,73.855100
1518,"Panchavati, Nashik",Maruti Constructions,Apartment,old,1.0,17.05,9.03,NaN,"Panchavati, Nashik, Maharashtra",20.016780,73.796650
1519,"Serene Meadows, Anandwalli Gaon,Nashik",Shri Balajee Buiders And Developers,Apartment,old,2.0,NaN,NaN,NaN,"Serene Meadows, Anandvalli, Nashik, Maharashtra",20.013280,73.736060
1520,"Makhmalabad, Nashik",Maa Buildwell,Apartment,old,2.0,NaN,NaN,NaN,"Makhmalabad, Makhamalabad, Nashik, Maharashtra",20.047230,73.775450
1521,"Nandur Village, Nashik",Shyam Buildcon Nashik,Apartment,old,1.0,NaN,NaN,NaN,"Nandur Village, Nandur, Nashik, Maharashtra",19.994530,73.843790
1522,"Nandur Village, Nashik",Elite Constructions Nashik,Apartment,old,2.0,NaN,NaN,NaN,"Nandur Village, Nandur, Nashik, Maharashtra",19.994530,73.843790
1523,"Ashwamegh Nagar, Makhmalabad,Nashik",Om Builders And Developers,Apartment,old,1.0,NaN,NaN,NaN,"Ashwamegh Nagar, Makhamalabad, Nashik, Maharas...",20.035230,73.790840
1524,"Vasantdadanagar, Adgaon,Nashik",Prathamesh Vivek Gangurde,Apartment,old,2.0,NaN,NaN,NaN,"Vasantdada Nagar, Adgaon, Nashik, Maharashtra",20.031780,73.855100
1525,"Shivaji Nagar, Satpur,Nashik",Bhagyalaxmi Builders And Developers,Apartment,old,1.0,NaN,NaN,NaN,"Shivaji Nagar, Satpur, Nashik, Maharashtra",20.003260,73.709240
1526,"Sadguru Nagar, Nashik",Dilip Veljibhai Patel,Apartment,old,1.0,NaN,NaN,NaN,"Sadguru Nagar, Satpur, Nashik, Maharashtra",20.006620,73.732700
1527,"Adgaon, Nashik",Sadguru Associates,Apartment,old,1.0,NaN,NaN,NaN,"Adgaon, Nashik, Maharashtra",20.036910,73.843840
1528,"Balawant Nagar, Anandwalli Gaon,Nashik",Shinde And Shinde Builders And Contractors,Apartment,old,2.0,NaN,NaN,NaN,"Balawant Nagar, Anandvalli, Nashik, Maharashtra",20.012770,73.739920
1529,"Nashik Road, Nashik",Pavan Construction,Apartment,old,1.0,NaN,NaN,NaN,"Nashik Road, Nashik, Maharashtra",19.955310,73.840890
1530,"Govind Nagar, Nashik",Rajeshbhai Gordhanbhai Makwana,Apartment,old,2.0,NaN,NaN,NaN,"Govind Nagar, Nashik, Maharashtra",19.983200,73.778830
1531,"Gurudatta Nagar, Nashik Road,Nashik",Gayatri Developers,Apartment,old,1.0,NaN,NaN,NaN,"Gurudatta Nagar, Dasak, Nashik, Maharashtra",19.980530,73.842530
1532,"Kamod Nagar, Indira Nagar,Nashik",Nilam Chandrakant Tejale,Apartment,old,2.0,37.79,20.01,NaN,"Kamod Nagar, Indira Nagar, Nashik, Maharashtra",19.976190,73.779000
1533,"Pokar Colony, Vaiduwadi,Nashik",Divyesh Pramod Kothari,Apartment,old,1.0,NaN,NaN,NaN,"Pokar Colony, Mhasrul, Nashik, Maharashtra",20.034570,73.805270
1534,"Deolali Gaon, Nashik",Karda Constructions,Apartment,old,1.0,NaN,NaN,NaN,"Deolali Gaon, Devlali, Nashik, Maharashtra",19.944270,73.832290
1535,"Adhav Nagar, Nashik Road,Nashik",Sai Home Builders,Apartment,old,1.0,NaN,NaN,NaN,"Adhav Nagar, Dasak, Nashik, Maharashtra",19.978050,73.836520
1536,"Tirumla Nagar, Wadala Gaon,Nashik",Unity Associates,Apartment,old,1.0,NaN,NaN,NaN,"Wadala, Nashik, Maharashtra",19.976930,73.798170
1537,"Serene Meadows, Anandwalli Gaon,Nashik",Dhatrak group,Apartment,old,3.0,6580.00,34.84,NaN,"Serene Meadows, Anandvalli, Nashik, Maharashtra",20.013280,73.736060
1538,"Gangapur, Nashik",Vira Enterprises,Apartment,old,1.0,11.82,6.26,NaN,"Gangapur, Nashik, Maharashtra",20.030860,73.716650
1539,"Damodar Nagar, Pathardi Phata,Nashik",New Akshara Construction,Apartment,old,1.0,NaN,NaN,NaN,"Damodar Nagar, Pathardi Phata, Nashik, Maharas...",19.947490,73.761390

In [57]:
df2.isnull().sum()

address             0
owners              2
housetype           0
house_condition     0
BHK                19
price               0
per_month_emi       2
total_sqft          1
cordinates          0
latitude            0
longitude           0
dtype: int64

In [58]:
df1 = pd.read_csv('df5',index_col=0)
df1

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft,cordinates,latitude,longitude
2000,"Hirawadi, Nashik",Ahirrao Buildcon,Apartment,old,1.0,NaN,NaN,NaN,"Hirawadi, Panchavati, Nashik, Maharashtra",20.01098,73.80851
2001,"Deolali Gaon, Nashik",ARKK Builders And Developers,Apartment,old,2.0,NaN,NaN,NaN,"Deolali Gaon, Devlali, Nashik, Maharashtra",19.94427,73.83229
2002,"Damodar Nagar, Pathardi Phata,Nashik",Deepak Pandurang Matale,Apartment,old,2.0,NaN,NaN,NaN,"Damodar Nagar, Pathardi Phata, Nashik, Maharas...",19.94749,73.76139
2003,"MIDC, Satpur,Nashik",Ganesh Tukaram Bolkar Builders And Developers,Apartment,old,2.0,NaN,NaN,NaN,"Satpur Midc, Satpur, Nashik, Maharashtra",19.99968,73.72605
2004,"Makhmalabad, Nashik",Mauli Builders And Developers,Apartment,old,2.0,NaN,NaN,NaN,"Makhmalabad, Makhamalabad, Nashik, Maharashtra",20.04723,73.77545
...,...,...,...,...,...,...,...,...,...,...,...
2495,"Shikrewadi ,Nashik Road, Nashik",Mr. Rahul Burse,Apartment,old,1.0,12.18,12.18,750.0,"Shikerwadi, Nashik, Maharashtra",19.96523,73.82785
2496,"Nashik Road, Nashik",Pushpak Kalantri,Apartment,old,2.0,20.65,20.65,1000.0,"Nashik Road, Nashik, Maharashtra",19.95531,73.84089
2497,"Nashik Road, Nashik","Astvinayak Real Estate,",Apartment,old,1.0,12.71,12.71,730.0,"Nashik Road, Nashik, Maharashtra",19.95531,73.84089
2498,"jijamata nagar,DattaMandir, Nashik Road,Nashik",Manish Dhruv,Apartment,old,1.0,11.65,11.65,645.0,Datta Mandir,19.95146,73.84069
2499,"Gandharva nagari,Nashik Road, Nashik",Manish Dhruv,Apartment,old,4.0,29.13,29.13,1294.0,"Gandharva Nagri, Sane Guruji Nagar, Nashik, Ma...",19.96435,73.83253

In [20]:
df1['cordinates']

0                                          Sheetal Vihar
1                                     Samraat Dream Citi
2                                          Surya Prakash
3      Nashik Road, Vadner Dumala, Nashik, Maharashtr...
4                       Nashik Road, Nashik, Maharashtra
                             ...
495                          Dwarka, Nashik, Maharashtra
496                     Ojhar, Niphd, Nashik, Maharashtr
497               Vijaynagar, Deola, Nashik, Maharashtra
498                      Panchavati, Nashik, Maharashtra
499        Kala Nagar, Indira Nagar, Nashik, Maharashtra
Name: cordinates, Length: 500, dtype: object

In [21]:
df3

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft,cordinates
1000,"CDO-MERI Colony, Nashik",AK Builders And Developers,Apartment,old,1.0,NaN,NaN,NaN,"(Meri Colony, Meri, Nashik, Maharashtra, (20.0..."
1001,"Shivshakti Nagar, Nashik",Shree Radhe Construction,Apartment,old,3.0,41.04,21.73,NaN,"(Shiv Shakti Nagar, Panchak, Nashik, Maharasht..."
1002,"Vijay Nagar, Nashik",Shree Krushna Builders And Developers,Apartment,old,1.0,19.22,10.18,NaN,"(Vijay Nagar, Chehdi, Nashik, Maharashtra, (19..."
1003,"Sinnar Taluka, Nashik",Samarth Buildcon,Apartment,old,1.0,NaN,NaN,NaN,"(Sinnar, Nashik, Maharashtra, (19.843690000000..."
1004,"Dwarka, Nashik",Om Sai Buildcon,Apartment,old,2.0,30.76,16.29,NaN,"(Dwarka, Nashik, Maharashtra, (19.993070000000..."
...,...,...,...,...,...,...,...,...,...
1495,"Patrakar Colony, Parijat Nagar,Nashik",DG Group And Shree Balaji Developers,Apartment,old,1.0,NaN,NaN,NaN,"(Patrakar Colony, Parijat Nagar, Nashik, Mahar..."
1496,"DGP Nagar, Nashik",Subhash Patil And Company,Apartment,old,1.0,NaN,NaN,NaN,"(DGP Nagar, Ambad, Nashik, Maharashtra, (19.96..."
1497,"Rehnuma Nagar, Nashik",Creative Constructions,Apartment,old,2.0,NaN,NaN,NaN,"(Rehanuma Nagar, Wadala, Nashik, Maharashtra, ..."
1498,"Rosa Colony, Nashik Road,Nashik",Ananda Buildcon,Apartment,old,4.0,NaN,NaN,NaN,"(Rosa Colony, (19.958830000000034, 73.83451000..."
1499,"Makhmalabad, Nashik",Omkar Residency,Apartment,old,1.0,NaN,NaN,NaN,"(Makhmalabad, Makhamalabad, Nashik, Maharashtr..."

In [22]:
df3['latitude'] = df3['cordinates'].apply(lambda x:x.latitude)
df3['longitude'] = df3['cordinates'].apply(lambda x:x.longitude)

In [24]:
df4['latitude'] = df4['cordinates'].apply(lambda x:x.latitude)
df4['longitude'] = df4['cordinates'].apply(lambda x:x.longitude)

In [23]:
df3

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft,cordinates,latitude,longitude
1000,"CDO-MERI Colony, Nashik",AK Builders And Developers,Apartment,old,1.0,NaN,NaN,NaN,"(Meri Colony, Meri, Nashik, Maharashtra, (20.0...",20.02679,73.80024
1001,"Shivshakti Nagar, Nashik",Shree Radhe Construction,Apartment,old,3.0,41.04,21.73,NaN,"(Shiv Shakti Nagar, Panchak, Nashik, Maharasht...",19.97732,73.84347
1002,"Vijay Nagar, Nashik",Shree Krushna Builders And Developers,Apartment,old,1.0,19.22,10.18,NaN,"(Vijay Nagar, Chehdi, Nashik, Maharashtra, (19...",19.93580,73.85298
1003,"Sinnar Taluka, Nashik",Samarth Buildcon,Apartment,old,1.0,NaN,NaN,NaN,"(Sinnar, Nashik, Maharashtra, (19.843690000000...",19.84369,73.99385
1004,"Dwarka, Nashik",Om Sai Buildcon,Apartment,old,2.0,30.76,16.29,NaN,"(Dwarka, Nashik, Maharashtra, (19.993070000000...",19.99307,73.80571
...,...,...,...,...,...,...,...,...,...,...,...
1495,"Patrakar Colony, Parijat Nagar,Nashik",DG Group And Shree Balaji Developers,Apartment,old,1.0,NaN,NaN,NaN,"(Patrakar Colony, Parijat Nagar, Nashik, Mahar...",19.99258,73.77201
1496,"DGP Nagar, Nashik",Subhash Patil And Company,Apartment,old,1.0,NaN,NaN,NaN,"(DGP Nagar, Ambad, Nashik, Maharashtra, (19.96...",19.96827,73.74230
1497,"Rehnuma Nagar, Nashik",Creative Constructions,Apartment,old,2.0,NaN,NaN,NaN,"(Rehanuma Nagar, Wadala, Nashik, Maharashtra, ...",19.98262,73.79375
1498,"Rosa Colony, Nashik Road,Nashik",Ananda Buildcon,Apartment,old,4.0,NaN,NaN,NaN,"(Rosa Colony, (19.958830000000034, 73.83451000...",19.95883,73.83451
1499,"Makhmalabad, Nashik",Omkar Residency,Apartment,old,1.0,NaN,NaN,NaN,"(Makhmalabad, Makhamalabad, Nashik, Maharashtr...",20.04723,73.77545

In [25]:
df4

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft,cordinates,latitude,longitude
1500,"Pimpalgaon Bahula, Nashik",Yogisai Construction,Apartment,old,1.0,NaN,NaN,NaN,"(Pimpalgaon Bahula, Nashik, Maharashtra, (19.9...",19.979460,73.708830
1501,"Pimpalgaon Bahula, Nashik",Nandan Devlopers,Apartment,old,1.0,NaN,NaN,NaN,"(Pimpalgaon Bahula, Nashik, Maharashtra, (19.9...",19.979460,73.708830
1502,"Professor Colony, Nashik",Jadhav Builders Nashik,Apartment,old,2.0,NaN,NaN,NaN,"(Professors Colony Road, Panchavati, Nashik, M...",20.017267,73.785088
1503,"Wasan Nagar, Pathardi Phata,Nashik",Sahyadri Buildcon Nashik,Apartment,old,1.0,NaN,NaN,NaN,"(Wasan Nagar, Pathardi Phata, Nashik, Maharash...",19.956910,73.762330
1504,"Makhmalabad, Nashik",Shree Sagar Associates,Apartment,old,1.0,NaN,NaN,NaN,"(Makhmalabad, Makhamalabad, Nashik, Maharashtr...",20.047230,73.775450
...,...,...,...,...,...,...,...,...,...,...,...
1995,"Pimpalgaon Bahula, Nashik",Chintamani Enterprises,Apartment,old,1.0,NaN,NaN,NaN,"(Pimpalgaon Bahula, Nashik, Maharashtra, (19.9...",19.979460,73.708830
1996,"Ambedkar Nagar, Chunchale,Nashik",N A Constructions Builder And Contractor,Apartment,old,1.0,NaN,NaN,NaN,"(Ambedkar Nagar, Chunchale, Nashik, Maharashtr...",19.964010,73.726480
1997,"MIDC Ambad, Nashik",Ambadas Sitaram Korade,Apartment,old,2.0,NaN,NaN,NaN,"(Midc Ambad Nashik, Ambad, Nashik, Maharashtra...",19.954960,73.744130
1998,"Indira Nagar, Nashik",Anand Group Builders And Developers,Apartment,old,NaN,NaN,NaN,NaN,"(Indira Nagar, Nashik, Maharashtra, (19.972190...",19.972190,73.783500
1999,"Jalapur, Nashik",ABH Developers,Apartment,old,3.0,NaN,NaN,NaN,"(Jalapur, Chandsi, Nashik, Maharashtra, (20.03...",20.033500,73.727640

In [50]:
df2

,address,owners,housetype,house_condition,BHK,price,per_month_emi,total_sqft,cordinates
500,"Ganesh Baba Nagar, Nashik",Jitendra Dadlani,Apartment,old,2.0,24.00,12.71,750.0,"Ganesh Baba Nagar, Wadala, Nashik, Maharashtra"
501,"Rajiv Nagar, Nashik",Ragini Chavan,Apartment,old,1.0,25.00,13.24,718.0,"Rajiv Nagar, Indira Nagar, Nashik, Maharashtra"
502,"Kalpataru Nagar, Nashik",Rajesh,Apartment,old,2.0,30.00,15.89,920.0,"Kalpataru Nagar, Wadala, Nashik, Maharashtra"
503,"College Road, Nashik",Kartik Anand,Apartment,old,4.0,110.00,54.61,1850.0,"College Road, Nashik, Maharashtra"
504,"New Pandit Colony, Nashik",Anil Mehta,Apartment,old,2.0,62.00,32.83,1000.0,"New Pandit Colony Road, Sharanpur, Nashik, Mah..."
...,...,...,...,...,...,...,...,...,...
995,"Kala Nagar, Indira Nagar,Nashik",Prathamesh Kulkarni,Apartment,old,3.0,52.00,27.54,1434.0,"Kala Nagar, Indira Nagar, Nashik, Maharashtra"
996,"Shivaji Nagar, Nashik",Shashikala Pagar,Apartment,old,1.0,15.00,7.94,580.0,"Shivaji Nagar, Satpur, Nashik, Maharashtra"
997,"Balawant Nagar, Anandwalli Gaon,Nashik",Mihir,Apartment,old,3.0,65.00,34.42,1700.0,"Balawant Nagar, Anandvalli, Nashik, Maharashtra"
998,"Pride Ganesh Row Houses,Nashik Road, Nashik",RAJESH KHEDKAR,Apartment,old,3.0,49.00,25.95,1490.0,Ganesh Row Houses
999,"Navnath Nagar, Nashik",Bhavik Group,Apartment,old,1.0,20.07,10.63,NaN,"Navnath Nagar, Ambad, Nashik, Maharashtra"